# Generated by Django 4.0.2 on 2022-02-27 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year_release', models.DateField()),
                ('vin_car', models.CharField(max_length=15, unique=True)),
                ('horse_power', models.IntegerField()),
                ('engine_size', models.IntegerField(verbose_name='engine_size in cm3')),
                ('foto_car', models.ImageField(blank=True, default='media/images/car/def-carPhoto.jpeg', null=True, upload_to='images/car/')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_driver', models.TextField(max_length=500)),
                ('model_car', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.car')),
                ('name_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
