# Generated by Django 4.0.1 on 2022-02-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(default=2000, verbose_name='engine_size in cm3'),
        ),
    ]
