# Generated by Django 4.0.1 on 2022-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_car_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_size in cm3',
            field=models.IntegerField(default=2000, max_length=10000),
        ),
        migrations.AddField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(default=200, max_length=1200),
        ),
    ]
