# Generated by Django 4.0.1 on 2022-02-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_car_engine_size in cm3_car_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size in cm3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(),
        ),
    ]
